# Generated by Django 4.2.1 on 2025-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcv', '0004_tag_alter_book_options_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
