# Generated by Django 4.2.1 on 2025-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcv', '0007_book_author_bio_book_author_photo_book_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.TextField(blank=True, help_text='Short description of the book', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
