# Generated by Django 4.2.1 on 2025-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcv', '0008_book_blurb_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Amazon page URL', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram page URL', null=True),
        ),
    ]
